### PR TITLE
empty

### PR DESCRIPTION
**Pull request by ablack12**
test ignored files

### CODE REVIEW

**Comment by ablack12** [comment]
evergreen retry

**Comment by ablack12** [comment]
evergreen retry

**Comment by ablack12** [comment]
evergreen retry

**Comment by ablack12** [comment]
evergreen retry

**Comment by ablack12** [comment]
evergreen retry

**Comment by ablack12** [comment]
evergreen retry

**Comment by ablack12** [comment]
evergreen help

**Comment by evrg-bot-webhook-dup** [comment]
### Evergreen comment commands
`evergreen retry` -- recreate PR patch`evergreen patch` -- use to create a PR patch when manual testing is enabled`evergreen refresh` -- resync PR statuses`evergreen merge` -- adds PR to the commit queue

**Comment by ablack12** [comment]
evergreen help

**Comment by evrg-bot-webhook-dup** [comment]
### Evergreen Comment Commands
`evergreen retry` 
  - attempt recreating PR patch
`evergreen refresh` 
  - resyncs PR Github checks
`evergreen merge` 
  - adds PR to the commit queue

**Comment by ablack12** [comment]
evergreen help

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- `evergreen retry` 
    - attempt recreating PR patch
- `evergreen refresh` 
    - resyncs PR Github checks
- `evergreen merge` 
    - adds PR to the commit queue

**Comment by ablack12** [comment]
evergreen help

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- `evergreen retry` 
    - attempt recreating PR patch
- `evergreen refresh` 
    - resyncs PR Github checks
- `evergreen merge` 
    - the commit queue is NOT enabled for this branch: this project is hecka disabled

**Comment by ablack12** [comment]
evergreen help

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- `evergreen retry` 
    - attempt recreating PR patch
- `evergreen patch` 
    - create a PR patch when manual testing is enabled
- `evergreen refresh` 
    - resyncs PR Github checks
- `evergreen merge` 
    - the commit queue is NOT enabled for this branch: this project is hecka disabled

**Comment by ablack12** [comment]
evergreen help

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- `evergreen retry, evergreen patch` 
    - attempt creating PR patch
- `evergreen refresh` 
    - resyncs PR Github checks
- `evergreen merge` 
    - the commit queue is NOT enabled for this branch: this project is hecka disabled

**Comment by ablack12** [comment]
evergreen help

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- `evergreen retry`, `evergreen patch` 
    - attempts to create a new PR patch
- `evergreen refresh` 
    - resyncs PR GitHub checks
- `~evergreen merge~` 
    - the commit queue is NOT enabled for this branch: this project is hecka disabled

**Comment by ablack12** [comment]
evergreen patch

**Comment by ablack12** [comment]
evergreen help

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- `evergreen retry` 
    - 
attempts to create a new PR patch; 
this is useful when something went wrong with automatically creating PR patches
- `evergreen refresh` 
    - resyncs PR GitHub checks
- ~`evergreen merge`~ 
    - the commit queue is NOT enabled for this branch: this project is hecka disabledhellohellothis project is hecka disabled

**Comment by evrg-bot-webhook** [comment]
### Available Evergreen Comment Commands

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- `evergreen retry`    - attempts to create a new PR patch; this is useful when something went wrong with automatically creating PR patches
- `evergreen refresh`    - resyncs PR GitHub checks
- ~`evergreen merge`~ 
    - the commit queue is NOT enabled for this branch: this project is hecka disabledhellohellothis project is hecka disabled

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- ~`evergreen merge`~ 
    - the commit queue is NOT enabled for this branch: this project is hecka disabledhellohellothis project is hecka disabled

**Comment by evrg-bot-webhook** [comment]
### Available Evergreen Comment Commands

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- ~`evergreen merge`~ 
    - the commit queue is NOT enabled for this branch: hmmmhellohellothis project is hecka disabled

**Comment by ablack12** [comment]
evergreen help

**Pull request closed without merging**
