### PR TITLE
Test commit queue enqueue comment

### PR DESCRIPTION
**Pull request by Kimchelly**

### CODE REVIEW

**Comment by Kimchelly** [comment]
evergreen help

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- `evergreen retry`    - attempts to create a new PR patch; this is useful when something went wrong with automatically creating PR patches
- `evergreen patch`    - attempts to create a new PR patch; this is required to create a PR patch when only manual PR testing is enabled
- `evergreen refresh`    - resyncs PR GitHub checks
- `evergreen merge`    - adds PR to the commit queue

**Comment by evrg-bot-webhook** [comment]
No commands available for this branch.

**Comment by Kimchelly** [comment]
evergreen merge

**Comment by evrg-bot-webhook-dup** [comment]
Evergreen could not enqueue your PR in the commit queue. The error:
some fake error happened while enqueueing

**Comment by evrg-bot-webhook-dup** [comment]
Evergreen could not enqueue your PR in the commit queue. The error:
some fake error happened while enqueueing

**Comment by Kimchelly** [comment]
evergreen help

**Comment by evrg-bot-webhook** [comment]
No commands available for this branch.

**Comment by evrg-bot-webhook-dup** [comment]
### Available Evergreen Comment Commands
- `evergreen retry`    - attempts to create a new PR patch; this is useful when something went wrong with automatically creating PR patches
- `evergreen patch`    - attempts to create a new PR patch; this is required to create a PR patch when only manual PR testing is enabled
- `evergreen refresh`    - resyncs PR GitHub checks
- `evergreen merge`    - adds PR to the commit queue

**Comment by Kimchelly** [comment]
evergreen merge

**Comment by evrg-bot-webhook-dup** [comment]
Evergreen could not enqueue your PR in the commit queue. The error:
PR is 'blocked'; branch protection settings are likely not met

**Comment by Kimchelly** [comment]
evergreen merge

**Pull request merged**
